# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://116.62.101.90:3306/property_management

    #url: jdbc:mysql://localhost:3306/property_management?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC

    url: jdbc:mysql://39.107.114.58:3306/property_management?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai

    username: root

    #password: root

    #password: 123

    password: root123456

mybatis-plus:
  type-aliases-package: org.wbk.propertymanagement.entity
  mapper-locations: classpath:/mapper/*.xml

uploadFile:
  location: D:/propertymanagementimg/
  resourceHandler: /upload/**
#thymeleaf:
#  prefix：classpath:/templates/:
#  suffix:.html:
#  cache：false: